version: "3.9"
services:
  first-redux-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/redux-shoppingcart-app
    # commandをコメントアウトしてからcreate-react-appしてフォルダ作ってるけど、すごい二度手間じゃね?
    command: sh -c "cd redux-shoppingcart-app && npm start"
    ports:
      - "3000:3000"
    stdin_open: true
